### ISSUE TITLE
Selecting image remove file input

### ISSUE THREAD

**Issue by ericnordelo** [SeregPie/VuetifyImageInput#1]
When the image is selected the file input is removed, after that i only can send the blob to server when i wnat to send the file object in a FormData to be parsed in my rails API.

Is this an expected behavior ?

How can I send the file to the server so ?

**Comment by SeregPie** [comment]
Yes. This is an expected behavior. I do it always this way. I overide the submit function, convert all the inputs and send the data with axios to the server.

**Comment by ericnordelo** [comment]
Yes but what data, the blob ? I need to sen d a file data to parse in the backend, how can I achieve this with sending the blob ?

**Comment by SeregPie** [comment]
Hello. I added a hidden input so one can send image data via form post requests.
