### ISSUE TITLE
Problem in import module with ts and vue-property-decorator

### ISSUE THREAD

**Issue by ldariom** [SeregPie/VuetifyImageInput#10]
Hello, 
I have problem in import module VuetifyImageInput from component.
![image](https://user-images.githubusercontent.com/14187352/63940605-2786ca80-ca6a-11e9-83ac-a882d7069759.png)

how can i do to import the component?

**Comment by SeregPie** [comment]
You are using TypeScript. If you want, you can make a pull request to add `index.d.ts`.

**Comment by ldariom** [comment]
Hello SeregPie
Thanks for answering.
How would it be to make an extraction request to add index.d.ts?

**Comment by ldariom** [comment]
Hello again SeregPie
I have solved it by importing this way:
`const component = require ("module");`
It would be convenient as you commented that the import could be done as you have detailed in the documentation.
Thank you
