### ISSUE TITLE
Latest NPM release (19.0.0) still errors out with Vuetify 2.0

### ISSUE THREAD

**Issue by juhasev** [SeregPie/VuetifyImageInput#12]
Wondering if the v19.0.0 includes the compatibility update for Vuetify 2.0? I am still getting errors after upgrading. I am using Vuetify 2.0.6.

[Vue warn]: Unknown custom element: <VIcon> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

**Comment by SeregPie** [comment]
Looks like you are using a-la-carte.
https://vuetifyjs.com/en/customization/a-la-carte

I guess a lot of people are using treeshaking. I will need to rework a few things. You must then import the component via `import VImageInput from 'vuetify-image-input/a-la-carte'` in the next version.

**Comment by juhasev** [comment]
No actually not, I am using the tree shaking method (which is now default). I was looking at your components and the way you render the components. Maybe it would be a good idea to switch to single page components where the interface is supposed to remain "compatible".

**Comment by SeregPie** [comment]
a-la-carte is threeshaking.

It's supported now.
```js
import VImageInput from 'vuetify-image-input/a-la-carte';
```

**Comment by juhasev** [comment]
Ok installed the latest version and the error for VImageInput is gone however now I get errors for more components. 

[Vue warn]: Unknown custom element: <VIcon>
[Vue warn]: Unknown custom element: <VBtn>
[Vue warn]: Unknown custom element: <VSpacer>
[Vue warn]: Unknown custom element: <VSlider>

All of these components are used in my application's single file templates.

While manual a-la-carte provides the same results as automatic tree shaking with Vuetify loader. It appears that Vuetify loader cannot resolved functional components automatically and I believe this is how Vuetify Image Input is written. Even if the package imports components manually I am suspecting that they will be included twice in the project increasing the bundle size (trying to research this now).

See the note about functional components below. (Recommended import is global import)

[https://vuetifyjs.com/en/customization/a-la-carte](https://vuetifyjs.com/en/customization/a-la-carte)
