### ISSUE TITLE
Vue2: v-icon

### ISSUE THREAD

**Issue by rhyswilliamsza** [SeregPie/VuetifyImageInput#14]
Hi There!

Apologies if this has been mentioned. `vicon` has since been renamed to `v-icon`. This causes the icons not to appear due to it being registered as a 'custom element'.

Thanks!

**Comment by rhyswilliamsza** [comment]
Neeeevermind,

Needed to import the a-la-carte plugin instead.

`import VImageInput from 'vuetify-image-input/a-la-carte';`

**Comment by SeregPie** [comment]
Glad it worked.

**Comment by julianlecalvez** [comment]
I have the vicon problem too, but the a-la-carte.js doesn't work for me. 
I also tried to import the component in my module : 
import { VBtn, VCard, VIcon, VProgressCircular, VSlider, VSpacer } from 'vuetify/lib';
but I get an "Unexpected identifier" error with the trace below 

I use it with Nuxt, so could be a Nuxt problem ? 
I checked the vuetify-image-input/a-la-carte.js exists in my node_modules/ folder. 

Any clue ? 

Thanks in advance ! 

EDIT : I only have the problem when I npm run build / start ! I can see the icons with npm run dev. 

```
vm.js:83:7 new Script
vm.js:277:10 createScript
vm.js:329:10 Object.runInThisContext
internal/modules/cjs/loader.js:710:26 Module._compile
internal/modules/cjs/loader.js:787:10 Module._extensions..js
internal/modules/cjs/loader.js:653:32 Module.load
internal/modules/cjs/loader.js:593:12 tryModuleLoad
internal/modules/cjs/loader.js:585:3 Module._load
internal/modules/cjs/loader.js:690:17 Module.require
internal/modules/cjs/helpers.js:25:18 require
webpack:/external "vuetify-image-input/a-la-carte":1: Object.vuetify-image-input/a-la-carte
webpack/bootstrap:25: __webpack_require__
pages/index.js:13:88 Module../node_modules/babel-loader/lib/index.js?!./node_modules/vue-loader/lib/index.js?!./pages/index.vue?vue&type=script&lang=js&
webpack/bootstrap:25: __webpack_require__
pages/index.vue:1: Module../pages/index.vue?vue&type=script&lang=js&
```

**Comment by geocare** [comment]
@julianlecalvez Did you manage to fix this issue? I'm facing the same issue.

**Comment by loiphong1996** [comment]
Clarify on this one
You use `import VImageInput from "vuetify-image-input/a-la-carte";` on the component you want to use this image input in.
Then register VImageInput to the component
`export default {
  name: "GenericComponent",
  components: {
    VImageInput
  }
}`

After this you can use 
` <v-image-input
            v-model="image"
          />`

This fix the issue of icon not appearing for me.

Versions:
- vue 2.6.12
- vuetify 2.2.11
- vuetify-image-input 19.2.2
