### ISSUE TITLE
Icons not rendering in build mode

### ISSUE THREAD

**Issue by arizorin** [SeregPie/VuetifyImageInput#17]
All mdi icons of this component are not rendering after build.
![image](https://user-images.githubusercontent.com/22889487/69523048-eff9c280-0f73-11ea-9aed-0669dade17a7.png)

**Comment by SeregPie** [comment]
Hi.
If you use treeshaking try this.
```js
import VImageInput from 'vuetify-image-input/a-la-carte';
```

**Comment by arizorin** [comment]
Thanks. Everything is fine now :)
