### ISSUE TITLE
Unclear how to install completely

### ISSUE THREAD

**Issue by mixmix** [SeregPie/VuetifyImageInput#18]
Hi, I have the basic installation in place ... I think? I don't know what I need to do to install the dependencies correctly. I've tried ignoring them, which works, but I get no icons similar to https://github.com/SeregPie/VuetifyImageInput/issues/3

If I try installing them, I'm not really sure how to do that, and there's no clear example code. Here's what I have, and this still leaves me without icons (while mdi icons are working fine with vuetify elsewhere in my app) : 

```js
import '@mdi/font/css/materialdesignicons.css' // Ensure you are using css-loader
import Vue from 'vue'
import Vuetify from 'vuetify/lib'

import VueClaw from 'vueclaw'
import VImageInput from 'vuetify-image-input'

Vue.use(Vuetify)

Vue.directive(VueClaw.name, VueClaw)
Vue.component(VImageInput.name, VImageInput)

export default new Vuetify({
  theme: {
    dark: true,
    themes: {
      dark: {
        primary: '#383838',
        secondary: '#A80000',
        accent: '#A70000',
        error: '#ff0000'
      }
    }
  },
  icons: {
    iconfont: 'mdi'
  }
})

```

I would recommend example code (somewhere) which has some complete setup for registering this to all work

**Comment by SeregPie** [comment]
If you are using treeshaking (`'vuetify/lib'`) use this snippet.

```js
import VImageInput from 'vuetify-image-input/a-la-carte';
```

**Comment by mixmix** [comment]
I've seen "a la carte" but don't know what it means. Is it french for ... something about choices on a menu?
yeah it's honestly a confusing phrase, is it a designed set-menu?

thanks for the reply

**Comment by SeregPie** [comment]
Look.
https://vuetifyjs.com/en/customization/a-la-carte#a-la-carte-treeshaking
