### ISSUE TITLE
Text-Align=center" messes up the image orientation

### ISSUE THREAD

**Issue by lupas** [SeregPie/VuetifyImageInput#19]
Thanks a lot for this great module :)

## Problem

When the components gets exposed to css `text-align: center`, the alignment of the uploaded image is wrong.

```html
<div class="text-center"> <!-- or somewhere in an element far above -->
  <VImageInput
    v-model="imageData"
  ></VImageInput>
</div>
```
<img width="309" alt="Screenshot 2020-02-24 at 15 53 49" src="https://user-images.githubusercontent.com/4020037/75162683-36e78780-571e-11ea-9a3a-2890e1ddb38c.png">

## Workaround
Can be manually fixed by adding a `text-left` class or `text-align: start` style.

```html
<div class="text-center">
  <VImageInput
    v-model="imageData"
    class="text-left"
  ></VImageInput>
</div>
```
<img width="309" alt="Screenshot 2020-02-24 at 15 56 40" src="https://user-images.githubusercontent.com/4020037/75162736-48309400-571e-11ea-8356-184c40abea6b.png">

I guess this could be easily fixed within the module itself, too.

**Comment by sankhaKarunasekara** [comment]
Thank you.! man you saved me.

**Comment by Kane-R-G** [comment]
Very nice catch :)

**Comment by juhasev** [comment]
I think the Vuerity image input should by default be a block element meaning you can place it into flex box container or any div really without any issues. It should render itself in an unopinated manner and not inherit any properties from the parent elements as some folks on this thread mentioned as potential workarounds. You cannot design an advanced component like this which is dependent on the physical size of the image. Therefore you should not let the client override the font size or determine the final presentation panel size. This size should be a prop of the component itself. For in house components we typically use a prop size that can be either small, medium or large. It becomes much easier to maintain your code when the parent component is not trying to inject behaviour or styling via CSS.

**Comment by SeregPie** [comment]
Should be fixed now.
