### ISSUE TITLE
Portrait Images Uploading in Landscape

### ISSUE THREAD

**Issue by jamesaharvey** [SeregPie/VuetifyImageInput#2]
When I'm uploading a photo that was taken in portrait mode on my phone, it shows up in landscape mode/sideways.  I am then unable to rotate the photo.  I've tried different height and width settings to try and get the image in there properly to no avail.  Please advise if there is something I can do to accommodate this.  Thanks!

**Comment by SeregPie** [comment]
Ok. The rotate function is back.
