### ISSUE TITLE
 Unknown custom element: <VIcon>, <VBtn> and <VSpacer>  and MDI icons not showing

### ISSUE THREAD

**Issue by whoismuktar** [SeregPie/VuetifyImageInput#23]
On registering  VuetifyImageInput globally or in any individual component, i get errors in console saying:

[Vue warn]: Unknown custom element: <VIcon> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

[Vue warn]: Unknown custom element: <VBtn> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

[Vue warn]: Unknown custom element: <VSpacer> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

Additionally, MDI-ICONS aren't showing

**Comment by SeregPie** [comment]
see #20 or #17
