### ISSUE TITLE
Nuxt Support

### ISSUE THREAD

**Issue by Mailines** [SeregPie/VuetifyImageInput#25]
Hi, 
I like this library alot, nice work but:
I use it with Nuxt and registered the component global as a plugin. With the DEV-Server everything works fine, but when I compile the application the upload-icon is not displayed and the element is not longer centered. 
What do I have to change? 

On DEV-Server
![image](https://user-images.githubusercontent.com/67375393/88849049-996f1300-d1e9-11ea-9113-3599905fe73a.png)

In Production: 
![image](https://user-images.githubusercontent.com/67375393/88849105-b0ae0080-d1e9-11ea-9344-66381aaefff3.png)

````
// ./plugins/v-image-input.js

import Vue from 'vue'
import VImageInput from 'vuetify-image-input'

Vue.component(VImageInput.name, VImageInput)
```

**Comment by Mailines** [comment]
Nevermind, using the a la carte treeshaking in the scope of the component fixed the issue. 👍 💯 
Maybe you can add this solution for NUXT to the docs.

**Comment by geocare** [comment]
@Mailines can you show me how to do it?

**Comment by Mailines** [comment]
@geocare 
Sorry for the late reply.
I have implemented it this way:


```vue
<template>
   <no-ssr>
      <v-image-input
         v-model="imageData"
         :image-quality="0.85"
         clearable
         :disabled="uploadImageLoading"
         />
   </no-ssr>
</template>

<script>
import VImageInput from 'vuetify-image-input/a-la-carte'

export default {
  ssr: false,
  components: {
    VImageInput
  }
}
</script>
```

In nuxt.config.js additionally add the library in the build block to transpile.

```js
// nuxt.config.js
build: {
    transpile: ['vuetify/lib', 'vuetify-image-input']
  },
```
I hope this helps.

**Comment by geocare** [comment]
Thanks! It worked! @Mailines
