### ISSUE TITLE
[BUG] Version 19.2.0 broke the module

### ISSUE THREAD

**Issue by MrNaif2018** [SeregPie/VuetifyImageInput#28]
Hi and thank you for your awesome module!
When upgrading to version 19.2.0 from 19.1.0 (I used `git bisect` to verify that exactly this change caused issues), the module stopped working.
When loading existing images into the v-model's variable, it is passed as a prop, but is not rendered. Also, when trying to upload an image, it says `Cannot read property file of null`

**Comment by SeregPie** [comment]
should be fixed now
