### ISSUE TITLE
Stable releases

### ISSUE THREAD

**Issue by juhasev** [SeregPie/VuetifyImageInput#31]
Could we get stable releases that are semantically versioned? I am not 100% sure I trust the master dev branch and it would be nice to target some releases like 1.1 or 1.2  etc.. which you can specify in your package.json file. This would also mean that when a breaking change is introduced you have to pump the version number to a new digit like 2.x. This prevents platforms like ours from pulling in breaking code before we have chance to migrate to the new version.

**Comment by SeregPie** [comment]
I do not plan to add any breaking changes to version 19 anymore.
I will fully rework the module in version 20. I will not delete but deprecate unused props, so it will still be working.
