### ISSUE TITLE
How to get uploaded filename

### ISSUE THREAD

**Issue by stnydesign** [SeregPie/VuetifyImageInput#4]
Hi

I would like to use VuetifyImageInput with firebase(storage).
Upload image to filebase needs image filename,but no properties in plugin to get filename. 
How to get uploaded image filename?

I appreciate you for using your plugin! thank you!!!

**Comment by SeregPie** [comment]
For now there is no way to get the file name using this component. What do you think, how should the API look like? Are there any examples with vue-uploader that do it?

**Comment by kinokomilk** [comment]
Thank you for your reply.

For example,this component can Implement it.
https://www.npmjs.com/package/vue-upload-component

Probably, input files "value" contains a file path,and use it.
I am sorry but details are unknown me...

**Comment by SeregPie** [comment]
it's better to wait until vuetify releases its own uploader component. then i can build image-input around it.
