### ISSUE TITLE
Module parse failed: Unexpected token

### ISSUE THREAD

**Issue by mariohmol** [SeregPie/VuetifyImageInput#43]
Hi there!

Trying to run `NODE_ENV=production node build/build.js ` and got this error
```
ERROR in ./node_modules/vuetify-image-input/index.js
Module parse failed: Unexpected token (1:16479)
You may need an appropriate loader to handle this file type.
```

Using this env:
* node: v14.19.1
* yarn: 1.22.18
* "vuetify-image-input": "^19.2.2",
*  "vuetify": "^2.6.4",

Any ideas?

Thanks a lot!

**Comment by SeregPie** [comment]
Hi. I need more info. Which builder do you use?

**Comment by mariohmol** [comment]
Webpack.. in this case I ended up removing the module, it actually wasnt been used in the project.. 

You can close if u wish!

thanks
