### ISSUE TITLE
resize slider not rendering in nuxt.js 2.6.1 build/start

### ISSUE THREAD

**Issue by itsensepk** [SeregPie/VuetifyImageInput#5]
Hi,
I'm very new to posting issues, so please dont mind the formatting.

when i build and start nuxt app, the resize slider vanishes and numbers come into view.
its working all good in dev mode, when i do npm run dev.

**my plugin vuetify-image-input.js file:**
import Vue from "vue";
import VImageInput from "vuetify-image-input";

Vue.component(VImageInput.name, VImageInput);

**my vuetify plugin file:**
import "@mdi/font/css/materialdesignicons.css";
import Vue from "vue";
import Vuetify from "vuetify";
import colors from "vuetify/es5/util/colors";
Vue.use(Vuetify, {
  iconfont:  .....
  theme: {
    .....
  }
});

**in config i call it like:**
{ src: "@/plugins/vuetify-image-input", ssr: false },

what can be the issue?
**in dev mode(working as expected):**
![3](https://user-images.githubusercontent.com/49489874/55893509-d0bf4800-5bd1-11e9-97dd-fd555445a31e.JPG)

**in build mode:**
![1](https://user-images.githubusercontent.com/49489874/55893198-3e1ea900-5bd1-11e9-8399-e58ec6db7def.JPG)
![2](https://user-images.githubusercontent.com/49489874/55893197-3d861280-5bd1-11e9-9b73-410ea41dc95e.JPG)

The slider gone! :/

**Comment by ribrewguy** [comment]
The slider also doesn't work on the demo

**Comment by SeregPie** [comment]
Hello.
Do you use Vuetify as a-la-carte?

**Comment by saikksub** [comment]
@itsensepk Can you share the component usage?
