### ISSUE TITLE
Read original Extension

### ISSUE THREAD

**Issue by Paulsky** [SeregPie/VuetifyImageInput#8]
I would like to preserve the original extension. Is it possible to check the original extension of the selected image? 

If I can read the original extension, than I'm able to set the image-format dynamically. Because I would like to set for example the image-format to GIF, if the original image is a GIF. But I don't want to set GIF as a default image-format.

**Edit 24 May:**

Turns out GIF is not working at all. It's been converted to a PNG file. Probably because canvas.toDataURL doesn't support GIFs. Maybe you can swap it with something else to get the base64 value; https://stackoverflow.com/questions/31280897/html5-canvas-todataurl-upload-gif-workaround or https://github.com/hongru/canvas2image

**Comment by saikksub** [comment]
@SeregPie I have created a new PR #27 to fix this issue.
