### ISSUE TITLE
How to get cropped image?

### ISSUE THREAD

**Issue by UsmanJavedAttari** [SeregPie/VuetifyImageInput#9]
Hey, I can get the cropped image? There's a button on the demo page, but in documentation, I didn't find it. Can anyone tell me how to get the cropped image? Probably there will a function.

**Comment by johnny-longneck** [comment]
Please post your answer, if you found one to this issue.

**Comment by ChrisCWerner** [comment]
You can get it from the `@input` event or with `v-model`. It returns a base64 png image.
